name: vankoo  # Este será el prefijo para redes, volúmenes y contenedores

services:
  # --- IAM Service ---
  iam-service:
    build:
      context: ../vankoo-iam-service
      dockerfile: Dockerfile
    hostname: iam-service
    networks:
      - main-network
    ports:
      - "${IAM_SERVICE_PORT:-8081}:8081" # El puerto de la izquierda es el de tu PC, el de la derecha es el del contenedor
    environment:
      IAM_SERVICE_HOST: ${IAM_SERVICE_HOST:-iam-service}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_DAYS: ${JWT_EXPIRATION_DAYS}
      IAM_DB_HOST: ${IAM_DB_HOST:-iam-db-postgres} # Usamos el nombre del servicio de la base de datos como hostname para la conexión
      IAM_DB_PORT: ${IAM_DB_PORT:-5432} # Puerto de la base de datos, configurable a través de variable de entorno o 5432 por defecto
      IAM_DB_NAME: ${IAM_DB_NAME:-vankoo_iam_db_dev} # Nombre de la base de datos, configurable a través de variable de entorno o 'vankoo_iam_db_dev' por defecto
      IAM_DB_USERNAME: ${IAM_DB_USERNAME:-admin} # Usuario para la base de datos, configurable a través de variable de entorno o 'admin' por defecto
      IAM_DB_PASSWORD: ${IAM_DB_PASSWORD:-password} # Contraseña para la base de datos, configurable a través de variable de entorno o 'password' por defecto
      KAFKA_HOST: ${KAFKA_HOST:-kafka-broker}
      KAFKA_INTERNAL_PORT: ${KAFKA_INTERNAL_PORT:-9094}
      DISCOVERY_SERVER_URL: ${DISCOVERY_SERVER_URL:-http://discovery-server:8761/eureka/}
    depends_on:
      iam-db-postgres:
        condition: service_started
      kafka-broker:
        condition: service_started
      discovery-server:
        condition: service_healthy # Espera a que Eureka esté listo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s # El IAM tarda un poco más en conectar a DB y Kafka
    restart: unless-stopped

  # --- IAM Database (PostgreSQL) ---
  iam-db-postgres:
    image: postgres:15 # Versión 15 estable
    networks: # Sirve para conectar este servicio con otros dentro de la misma red, permitiendo que se comuniquen entre sí usando los nombres de servicio como hostnames
      - main-network
    volumes:
      - iam-db-data:/var/lib/postgresql/data # La izquierda significa el nombre del volumen, la derecha es la ruta dentro del contenedor donde se almacenan los datos de Postgres
    environment:
      POSTGRES_DB: ${IAM_DB_NAME:-vankoo_iam_db_dev}
      POSTGRES_USER: ${IAM_DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${IAM_DB_PASSWORD:-password} # Usa variable o 'password' por defecto
    ports:
      - "${IAM_DB_PORT:-5432}:5432"

  invoicing-db-mongo:
    image: mongo:7.0
    networks:
      - main-network
    volumes:
      - invoicing-db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${INVOICING_DB_NAME:-vankoo_invoicing_db_dev}
      MONGO_INITDB_ROOT_USERNAME: ${INVOICING_DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${INVOICING_DB_PASSWORD:-password}
    ports:
      - "${INVOICING_DB_PORT:-27017}:27017"

  finance-cache-redis:
    image: redis:7.4.7-alpine
    networks:
      - main-network
    volumes:
      - finance-redis-data:/data
    ports:
      - "${FINANCE_REDIS_PORT:-6379}:6379"

  # --- MENSAJERÍA (KAFKA) ---
  kafka-broker:
    image: apache/kafka:4.1.1
    networks:
      - main-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "${KAFKA_EXTERNAL_PORT:-9092}:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Configuración de Red (Listeners)
      # 9092: Tu PC | 9094: Microservicios | 9093: Gestión interna
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka-broker:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Configuración KRaft (Sin Zookeeper)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Identificador único del cluster (Obligatorio en Apache)
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID:-vankoo-dev-cluster-2026}

      # Optimización para Desarrollo
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    networks:
      - main-network
    ports:
      - "${KAFKA_UI_PORT:-9000}:8080" #El puerto de la izquierda es el de tu PC, el de la derecha es el del contenedor
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME:-vankoo-dev-cluster}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9094
    depends_on:
      - kafka-broker

  # --- DISCOVERY SERVER (Eureka) ---
  discovery-server:
    build:
      context: ../vankoo-discovery-server
      dockerfile: Dockerfile
    hostname: discovery-server
    networks:
      - main-network
    ports:
      - "${DISCOVERY_SERVER_PORT:-8761}:8761"
    healthcheck: # Sirve para que Docker pueda verificar si el servicio está listo para recibir tráfico. Es especialmente útil para servicios que tardan en arrancar, como los basados en Java.
      # Apuntamos al endpoint específico de readiness
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health/readiness"] # Usamos el endpoint de readiness para asegurarnos de que el servicio no solo esté "vivo" sino también listo para manejar solicitudes
      interval: 30s # Frecuencia con la que Docker realizará el health-check
      timeout: 10s # Tiempo máximo que Docker esperará para recibir una respuesta antes de considerar el health-check como fallido
      retries: 3 # Número de intentos fallidos antes de marcar el contenedor como no saludable
      start_period: 20s # Tiempo de espera inicial para que el servicio arranque antes de comenzar a hacer health-checks
    restart: unless-stopped # Política de reinicio para asegurar que el servicio se mantenga activo incluso si falla

  # --- API Gateway (Spring Cloud Gateway) ---
  api-gateway:
    build:
      context: ../vankoo-api-gateway
      dockerfile: Dockerfile
    hostname: api-gateway
    networks:
      - main-network
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    environment:
      DISCOVERY_SERVER_URL: ${DISCOVERY_SERVER_URL:-http://discovery-server:8761/eureka/}
    depends_on:
      discovery-server:
        condition: service_healthy # Espera a que Eureka esté listo antes de arrancar el API Gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness"] # Verifica que el API Gateway esté listo para recibir tráfico
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

# --- Definición de Redes y Volúmenes ---
networks:
  main-network:
    name: main-network
    driver: bridge

volumes:
  iam-db-data:
  invoicing-db-data:
  finance-redis-data:
  kafka-data:
    driver: local